- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest
- name: enable and start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
- name: delete default file
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
- name: download front end code and unarchive
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html
    remote_src: yes
- name: copy front end code
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
    - restart nginx

# - name: restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted