- name: install MySql server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest
- name: MySql enable and start
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
- name: install python mysql dependencies
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography #To use passwords in command line we need to install cryptography
    executable: pip3.9 #pip3.11 if python version is 3.11 
# Check root password already set up or not
- name: check db connections
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    filter: version
  ignore_errors: yes
  register: mysql_connection_output
- name: print mysql output
  ansible.builtin.debug:
    msg: "output is: {{ mysql_connection_output }}"
- name: setup root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
  when: mysql_connection_output.failed is true #Don't give {{ }} in when condition